name: Build and push images to Quay.io registry
on:
  push:
    branches:
      - test-multi-arch-review-comments
  schedule:
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
    # Schedule build to 1:00 each Tuesday
    - cron: '0 1 * * 2'
jobs:
  build-and-push:
    # To not run in forks
    #if: github.repository_owner == 'sclorg'
    name: Build and push s2i containers
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: "Dockerfile"
            registry_namespace: "morana"
            tag: "centos7"
            quayio_username: "morana"
            quayio_token: "YmD1tG5YJro4zu/B9AYVLY9S1Rk0aCnuqwvzu154rjwaCk9E6OU19RFGd9VYEYcgb25DY9DEQO1T12GPxdv1vQ=="
            suffix: "-centos7"
          - dockerfile: "Dockerfile.c9s"
            registry_namespace: "morana"
            tag: "c9s"
            quayio_username: "morana"
            quayio_token: "YmD1tG5YJro4zu/B9AYVLY9S1Rk0aCnuqwvzu154rjwaCk9E6OU19RFGd9VYEYcgb25DY9DEQO1T12GPxdv1vQ=="
            suffix: "-c9s"
          - dockerfile: "Dockerfile.c8s"
            registry_namespace: "morana"
            tag: "c8s"
            quayio_username: "morana"
            quayio_token: "YmD1tG5YJro4zu/B9AYVLY9S1Rk0aCnuqwvzu154rjwaCk9E6OU19RFGd9VYEYcgb25DY9DEQO1T12GPxdv1vQ=="
            suffix: "-c8s"
          - dockerfile: "Dockerfile.fedora"
            registry_namespace: "morana"
            quayio_username: "morana"
            quayio_token: "YmD1tG5YJro4zu/B9AYVLY9S1Rk0aCnuqwvzu154rjwaCk9E6OU19RFGd9VYEYcgb25DY9DEQO1T12GPxdv1vQ=="

    steps:
      - name: Automatic tag detection for Fedora images
        id: tag
        shell: bash
        run: |
          if [[ ${{ matrix.dockerfile }} == "Dockerfile.fedora" ]]
          then
            _version=`curl https://raw.githubusercontent.com/sclorg/s2i-base-container/master/core/Dockerfile.fedora | grep ^FROM`
            _tag=`echo $_version | cut -d: -f2`
          else
            _tag=${{ matrix.tag }}
          fi
          echo "tag=${_tag}" >> $GITHUB_OUTPUT
          
      - name: Check if dockerfile is c9s , then build & push s2i-core for multi-arch
        if: matrix.dockerfile == 'Dockerfile.c9s'
        uses: sclorg/build-and-push-action@v4
        with:
          registry: "quay.io"
          registry_namespace: ${{ matrix.registry_namespace }}
          registry_username: ${{ matrix.quayio_username }}
          registry_token: ${{ matrix.quayio_token }}
          dockerfile: "core/${{ matrix.dockerfile }}"
          image_name: "s2i-core${{ matrix.suffix }}"
          tag: ${{ steps.tag.outputs.tag }}
          archs: ppc64le, s390x

        uses: sclorg/build-and-push-action@v4
        with:
          registry: "quay.io"
          registry_namespace: ${{ matrix.registry_namespace }}
          registry_username: ${{ matrix.quayio_username }}
          registry_token: ${{ matrix.quayio_token }}
          dockerfile: "core/${{ matrix.dockerfile }}"
          image_name: "s2i-core${{ matrix.suffix }}"
          tag: ${{ steps.tag.outputs.tag }}

      - name: Build and push s2i-base to quay.io registry
        uses: sclorg/build-and-push-action@v4
        with:
          registry: "quay.io"
          registry_namespace: ${{ matrix.registry_namespace }}
          registry_username: ${{ matrix.quayio_username }}
          registry_token: ${{ matrix.quayio_token }}
          dockerfile: "base/${{ matrix.dockerfile }}"
          image_name: "s2i-base${{ matrix.suffix }}"
          tag: ${{ steps.tag.outputs.tag }}
